@startuml Database Schema
    entity "Organizations" as organizations {
        * organization_id: UUID <<PK>> <<generated>>
        --
        * name_legal: VARCHAR(255)
        * name_trading: VARCHAR(255)
        * name_short: VARCHAR(255)
        * name_prefix_code: VARCHAR(50)
        * name_prefix_description: VARCHAR(255)
        
        * type_code: VARCHAR(10) <<FK>>
        * sub_type_code: VARCHAR(10) <<FK>>
        * accounting_sector_code: VARCHAR(10) <<FK>>
        
        * operation_country_code: VARCHAR(2)
        
        * economic_activity_category_code: VARCHAR(2) <<FK>>
        * economic_activity_sub_category_code: VARCHAR(2) <<FK>>

        * audit_creation_date_time: VARCHAR(20)
        * audit_last_update_date_time: VARCHAR(20)
    }

    entity "Organization Types" as organizationTypes {
        * type_code: VARCHAR(10) <<PK>>
        --
        * type_description: VARCHAR(255)
    }

    entity "Organization SubTypes" as organizationSubTypes {
        * sub_type_code: VARCHAR(10) <<PK>>
        --
        * sub_type_description: VARCHAR(255)
    }

    entity "Organization Accounting Sectors" as organizationAccountingSectors {
        * accounting_sector_code: VARCHAR(10)
        --
        * accounting_sector_description: VARCHAR(255)
    }

    entity "Organization Economic Activity Categories" as organizationEconomicActivityCategories {
        * economic_activity_category_code: VARCHAR(2) <<PK>>
        --
        * economic_activity_category_description: VARCHAR(255)
    }

    entity "Organization Economic Activity SubCategories" as organizationEconomicActivitySubCategories {
        * economic_activity_sub_category_code: VARCHAR(2) <<PK>>
        --
        * economic_activity_sub_category_description: VARCHAR(255)
    }

    organizations }|--|| organizationTypes
    organizations }|--|| organizationSubTypes
    organizations }|--|| organizationAccountingSectors
    organizations }|--|| organizationEconomicActivityCategories
    organizations }|--|| organizationEconomicActivitySubCategories

    entity "Applicants" as applicants {
        * applicant_id: UUID <<PK>> <<generated>>
        --
        * session_id: VARCHAR(50)
        * application_type: VARCHAR(3)
        * organization_id: UUID <<FK>>

        * person_name_prefix_code: VARCHAR(10) <<FK>>
        * person_given_name: VARCHAR(255)
        * person_middle_name: VARCHAR(255)
        * person_last_name: VARCHAR(255)
        * person_birth_name: VARCHAR(255)

        * gender_code: VARCHAR(2) <<FK>>

        * birth_date: VARCHAR(10)
        * birth_place_country_code: VARCHAR(2) <<FK>>

        * residence_country_code: VARCHAR(2) <<FK>>
        * civil_status_code: VARCHAR(5) <<FK>>
        * occupation_code: VARCHAR(5) <<FK>>
        * accounting_sector_code: VARCHAR(5) <<FK>>

        * employment_status_code: VARCHAR(5) <<FK>>
        * employment_start_date: VARCHAR(10)
        * employment_employeer_name: VARCHAR(255)
        * employment_employeer_activity_category_code: VARCHAR(2) <<FK>>
        * employment_employeer_control_stake_indicator: BOOLEAN

        * residential_status_code: VARCHAR(2) <<FK>>

        * finance_number_of_dependents: SMALLINT
        * finance_total_expenses_amount: SMALLINT
        * finance_total_expenses_currency: VARCHAR(3)

        * audit_creation_date_time: VARCHAR(20)
        * audit_last_update_date_time: VARCHAR(20)
    }

    entity "Applicant Genders" as applicantGenders {
        * gender_code: VARCHAR(2) <<PK>>
        --
        * gender_description: VARCHAR(6)
    }

    applicants }|--|| applicantGenders

    entity "Applicant Income" as applicantIncomes {
        * applicant_income_id: UUID <<PK>> <<generated>>
        --
        * applicant_id: UUID
        * income_type: VARCHAR(5) <<FK>>
        * income_amount: SMALLINT
        * income_currency: VARCHAR(3)
    }

    applicants ||--|{ applicantIncomes

    entity "Applicant Income Types" as applicantIncomeTypes {
        * income_type_code: VARCHAR(5) <<PK>>
        --
        * income_type_description: VARCHAR(255)
    } 

    applicantIncomes }|--|| applicantIncomeTypes

    entity "Applicant Civil Statutes" as applicantCivilStatutes {
        * civil_status_code: VARCHAR(5) <<PK>>
        --
        * civil_status_description: VARCHAR(255)
    }

    applicants }|--|| applicantCivilStatutes

    entity "Applicant Name Prefixes" as applicantNamePrefixes {
        * name_prefix_code: VARCHAR(10) <<PK>>
        --
        * name_prefix_description: VARCHAR(255)
    }

    applicants }|--|| applicantNamePrefixes

    entity "Applicant Name Aliases" as applicantNameAliases {
        * name_alias_id: UUID <<PK>> <<generated>>
        --
        * applicant_id: UUID <<FK>>
        * name_alias: VARCHAR(255)
    }

    entity "Applicant Nationalities" as applicantNationalities {
        * nationality_id: UUID <<PK>> <<generated>>
        --
        * applicant_id: UUID <<FK>>
        * nationality_order: SMALLINT
        * nationality_code: VARCHAR(2)
    }

    entity "Applicant Foreign Taxes" as applicantForeignTaxes {
        * foreign_tax_id: UUID <<PK>> <<generated>>
        --
        * applicant_id: UUID <<FK>>
        * foreign_tax_order: SMALLINT

        * country_code: VARCHAR(2)
        * document_number: VARCHAR(100)
    }

    entity "Applicant Postal Addresses" as applicantPostalAddresses {
        * postal_address_id: UUID <<PK>> <<generated>>
        --
        * applicant_id: UUID <<FK>>
        * address_type_code: VARCHAR(10) <<FK>>
    }

    entity "Applicant Postal Address Types" as applicantPostalAddressTypes {
        * address_type_code: VARCHAR(10)
        --
        * address_type_description: VARCHAR(255)
    }

    applicantPostalAddresses }|--|| applicantPostalAddressTypes

    entity "Applicant Phone Addresses" as applicantPhoneAddresses {
        * phone_address_id: UUID <<PK>> <<generated>>
        --
        * applicant_id: UUID <<FK>>

        * mobile_number: VARCHAR(35)
        * phone_number: VARCHAR(35)
        * international_code: VARCHAR(4)
    }

    entity "Applicant Electronic Addresses" as applicantElectronicAddresses {
        * electronic_address_id: UUID <<PK>> <<generated>>
        --
        * applicant_id: UUID <<FK>>
        * electronic_address_main: BOOLEAN
        * email_address: VARCHAR(256)
    }

    entity "Applicant Employment Statutes" as applicantEmploymentStatutes {
        * employment_status_code: VARCHAR(5) <<PK>>
        --
        * employment_status_description: VARCHAR(255)
    }

    applicants }|--|| organizations
    applicants ||--|{ applicantNameAliases
    applicants ||--|{ applicantNationalities
    applicants ||--|{ applicantForeignTaxes
    applicants ||--|{ applicantPostalAddresses
    applicants ||--|{ applicantPhoneAddresses
    applicants ||--|{ applicantElectronicAddresses
    applicants }|--|| applicantEmploymentStatutes
    applicants }|--|| organizationEconomicActivityCategories
    applicants }|--|| organizationEconomicActivitySubCategories
@enduml