@startuml Customer Service - As To Be
    title: Customer Service - As To Be

    () "GET /customers\nGET /customers?email={email}\nPOST /customers\nPUT /customers/{customerId}" as customerEndpoints
    () "GET /customers/{customerId}/persons\nPOST /customers/{customerId}/persons\nPATCH /customers/{customerId}/persons/patch\nPATCH /customers/{customerId}/persons/ddv-review-patch\nPOST /customers/{customerId}/check-existing-customer" as personEndpoints
    () "GET /customers/{customerId}/business\nPOST /customers/{customerId}/business\nPATCH /businesses/{businessId}" as businessEndpoints

    () "Credit Application Service Client" as creditApplicationServiceClient
    () "SIC Code Service Client" as sicCodeServiceClient
    () "Address Service Client" as addressServiceClient
    () "BaaS Service Client" as baasServiceClient

    () "Business Events Topic" as businessEventsTopic
    () "Customer Events Topic" as customerEventsTopic
    () "Person Events Topic" as personEventsTopic

    package "Customer Service REST API" {
        [Customer Controller] as customerController
        [Customer Service] as customerService
        customerController -up-> customerEndpoints
        customerController -down-> customerService
        customerService -down-( customerEventsTopic

        [Person Controller] as personController
        [Person Service] as personService
        personController -up-> personEndpoints
        personController -down-> personService
        personService -down-( creditApplicationServiceClient
        personService -down-( sicCodeServiceClient
        personService -down-( addressServiceClient
        personService -down-( personEventsTopic
        personService -down-( baasServiceClient

        [Business Controller] as businessController
        [Business Service] as businessService
        businessController -up-> businessEndpoints
        businessController -down-> businessService
        businessService -down-( businessEventsTopic
    }

    package "3-rd parties" {
        [Credit Application Service] as creditApplicationService
        creditApplicationService -up-> creditApplicationServiceClient

        [SIC Code Service] as sicCodeService
        sicCodeService -up-> sicCodeServiceClient

        [Address Service] as addressService
        addressService -up-> addressServiceClient

        [BaaS Service] as baasService
        baasService -up-> baasServiceClient

        [Kafka] as kafka
        kafka -up-> businessEventsTopic
        kafka -up-> customerEventsTopic
        kafka -up-> personEventsTopic
    }
@enduml