@startuml Get an existing organization
    title Get an existing organization

    actor User as user
    participant OrganizationController as organizationController
    participant OrganizationService as organizationService
    participant OrganizationRepository as organizationRepository
    database MongoDB as db

    user -> organizationController: Organization ID in the query string
        organizationController -> organizationService: ID of organization to retrieve

            organizationService -> organizationRepository: ID of organization to retrieve
                organizationRepository -> db: ID of record to retrieve
                db -> organizationRepository: Organization's DTO from DB
            organizationRepository -> organizationService: Organization DTO from DB

            alt Organization with given ID was not found
                organizationService -> organizationService: Throw an instance of Not Found Exception
            end 

        organizationService -> organizationController: Organization DTO
    organizationController -> user: Organization DTO
@enduml