@startuml Create a new organization
    title Create a new organization

    actor User as user
    participant OrganizationController as organizationController
    participant OrganizationService as organizationService
    participant OrganizationValidator as organizationValidator
    participant OrganizationRepository as organizationRepository
    database MongoDB as db
    queue Kafka as kafka

    user -> organizationController: Organization DTO in the request body
        organizationController -> organizationService: Organization DTO to create

            organizationService -> organizationValidator: Validate the incoming Organization DTOs
            alt Validation failure
                organizationValidator -> organizationValidator: Throw an instance of Validation Exception
            end

            organizationService -> organizationRepository: Save Organization DTO
                organizationRepository -> db: Insert record
                db -> organizationRepository: Saved record
            organizationRepository -> organizationService: Saved Organization DTO

            organizationService -> kafka: Organization created event

        organizationService -> organizationController: Created Organization DTO
    organizationController -> user: 201 CREATED response code and Location header
@enduml