@startuml Create a new organization
    title Create a new organization

    actor User as user
    participant OrganizationController as organizationController
    participant OrganizationService as organizationService
    participant OrganizationMapper as organizationMapper
    participant OrganizationValidator as organizationValidator
    participant OrganizationRepository as organizationRepository
    database PostgreSQL as db

    user -> organizationController: OrganizationDTO in the request body
        organizationController -> organizationService: OrganizationDTO to create

            organizationService -> organizationValidator: Validate the incoming OrganizationDTOs
            alt Validation failure
                organizationValidator -> organizationValidator: Throw an instance of Validation Exception
            end

            organizationService -> organizationMapper: Map OrganizationDTO to Organization entity
            organizationMapper -> organizationService: Mapper Organization entity

            organizationService -> organizationRepository: Save Organization entity
                organizationRepository -> db: Insert record
                db -> organizationRepository: Saved record
            organizationRepository -> organizationService: Saved Organization entity

            organizationService -> organizationMapper: Map Organization entity to OrganizationDTO
            organizationMapper -> organizationService: Mapped OrganizationDTO

        organizationService -> organizationController: Created OrganizationDTO
    organizationController -> user: 201 CREATED response code and Location header
@enduml