@startuml Create a new applicant
    title Create a new applicant

    actor User as user
    participant ApplicantController as applicantController
    participant ApplicantService as applicantService
    participant ApplicantMapper as applicantMapper
    participant ApplicantValidator as applicantValidator
    participant ApplicantRepository as applicantRepository
    database PostgreSQL as db

    user -> applicantController: Applicant DTO in the request body
        applicantController -> applicantService: Applicant DTO to create

            applicantService -> applicantValidator: Validate the incoming Applicant DTO
            alt Validation failure
                applicantValidator -> applicantValidator: Throw an instance of Validation Exception
            end

            applicantService -> applicantMapper: Map Applicant DTO to Applicant entity
            applicantMapper -> applicantService: Mapper Applicant entity

            applicantService -> applicantRepository: Save Applicant entity
                applicantRepository -> db: Insert record
                db -> applicantRepository: Saved record
            applicantRepository -> applicantService: Saved Applicant entity

            applicantService -> applicantMapper: Map Applicant entity to Applicant DTO
            applicantMapper -> applicantService: Mapped Applicant DTO

        applicantService -> applicantController: Created Applicant DTO
    applicantController -> user: 201 CREATED response code and Location header
@enduml