@startuml Create a new applicant
    title Create a new applicant

    actor User as user
    participant ApplicantController as applicantController
    participant ApplicantService as applicantService
    participant ApplicantValidator as applicantValidator
    participant ApplicantRepository as applicantRepository
    database MongoDB as db
    queue Kafka as kafka

    user -> applicantController: Applicant DTO in the request body
        applicantController -> applicantService: Applicant DTO to create

            applicantService -> applicantValidator: Validate the incoming Applicant DTO
            alt Validation failure
                applicantValidator -> applicantValidator: Throw an instance of Validation Exception
            end

            applicantService -> applicantRepository: Save Applicant DTO
                applicantRepository -> db: Insert record
                db -> applicantRepository: Saved record
            applicantRepository -> applicantService: Saved Applicant DTO

            applicantService -> kafka: Applicant created event

        applicantService -> applicantController: Created Applicant DTO
    applicantController -> user: 201 CREATED response code and Location header
@enduml